kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: npm-proxy-cache-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: npm-proxy-cache
    spec:
      containers:
      - name: kubernetes-npm-proxy-cache
        image: elthariel/kubernetes-npm-proxy-cache:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
kind: Service
apiVersion: v1
metadata:
  name: npm-proxy-cache-service
spec:
  selector:
    app: npm-proxy-cache
  ports:
    - name: 'http'
      protocol: 'TCP'
      port: 80
      targetPort: 8080
    - name: 'https'
      protocol: 'TCP'
      port: 443
      targetPort: 8080
