kind: Deployment
apiVersion: v1
metadata:
  name: npm-proxy-cache-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: npm-proxy-cache
    spec:
      containers:
      - name: kubernetes-npm-proxy-cache
        image: elthariel/kubernetes-npm-proxy-cache:latest
        ports:
        - containerPort: 8080
      hard:
        requests.cpu: 0.1
        requests.memory: 256Mi
        limits.cpu: 0.2
        limits.memory: 256Mi
---
kind: Service
apiVersion: v1
metadata:
  name: npm-proxy-cache-service
spec:
  selector:
    app: npm-proxy-cache
  ports:
    - name: 'http'
      protocol: 'TCP'
      port: 80
      targetPort: 8080
    - name: 'https'
      protocol: 'TCP'
      port: 443
      targetPort: 8080
